[pytest]
addopts = -v
markers =
    password_recovery: тесты сценариев восстановления пароля
    personal_account: тесты личного кабинета
    main_functionality: основные пользовательские сценарии
    feed: проверки раздела "Лента заказов"
